server:
  port: 8181


spring:
  data:
    mongodb:
      host: 116.62.144.245
      port: 27017
      database: admin
      username: admin
      password: test
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
  profiles: default